"""Add contact identity and relationship engine

Revision ID: 60be54339166
Revises: 
Create Date: 2026-09-22 21:17:16.672578

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '60be54339166'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
